#  python bottleapi1.py

# -*- coding: utf-8 -*-
"""pathfinding_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SP3P7CLMItx956RYeGmRc5sd2iHGzLe3
"""

# !pip install -q sentence-transformers
#
# !pip install -q ace-tools

osm_path = "gmu.xml"

import xml.etree.ElementTree as ET
import json
from collections import defaultdict
import os
from bottle import Bottle, request, response, run
from semantic_search import get_top_n_tags, get_waypoints_for_tags

osmFile = "gmu.xml"
tree = ET.parse(osmFile)
root = tree.getroot()

tag_dict = defaultdict(set)

for element in root.iter():
    if element.tag in {"node", "way", "relation"}:
        for tag in element.findall("tag"):
            k = tag.attrib.get("k")
            v = tag.attrib.get("v", "")
            if k is not None:
                tag_dict[k].add(v)

tag_dict_json = {k: sorted(list(v_set)) for k, v_set in tag_dict.items()}

with open("osm_tags_sorted.json", "w") as f:
    json.dump(tag_dict_json, f, indent=2)

print("success")

from sentence_transformers import SentenceTransformer, util
import json

with open("osm_tags_sorted.json", "r") as f:
    tag_dict = json.load(f)

tag_texts = [f"{k}={v}" for k, values in tag_dict.items() for v in values]

model = SentenceTransformer('all-MiniLM-L6-v2')

tag_embeddings = model.encode(tag_texts, convert_to_tensor=True)

import pandas as pd
import networkx as nx
from geopy.distance import geodesic

tree = ET.parse("gmu.xml")
root = tree.getroot()

node_lookup = {}
for node in root.findall("node"):
    node_id = node.attrib["id"]
    lat = float(node.attrib["lat"])
    lon = float(node.attrib["lon"])
    node_lookup[node_id] = (lat, lon)

G = nx.Graph()
for way in root.findall("way"):
    tags = {tag.attrib["k"]: tag.attrib["v"] for tag in way.findall("tag")}
    if (
        tags.get("highway") in {"footway", "path", "corridor", "pedestrian"}
        and tags.get("highway") != "steps"
        and tags.get("ramp:wheelchair") != "no"
        and tags.get("wheelchair") != "no"
    ):
        nds = [nd.attrib["ref"] for nd in way.findall("nd")]
        for i in range(len(nds) - 1):
            n1, n2 = nds[i], nds[i + 1]
            if n1 in node_lookup and n2 in node_lookup:
                coord1, coord2 = node_lookup[n1], node_lookup[n2]
                dist = geodesic(coord1, coord2).meters
                G.add_edge(n1, n2, weight=dist)

app = Bottle()

def get_waypoints(user_prompt: str):
    user_input = user_prompt
    prompt_embedding = model.encode(user_input, convert_to_tensor=True)
    cosine_scores = util.cos_sim(prompt_embedding, tag_embeddings)[0]

    top_k = 10
    top_indices = cosine_scores.argsort(descending=True)[:top_k]
    tag_texts_top = [tag_texts[i] for i in top_indices]
    top_matches = [{"k": tag.split("=")[0], "v": tag.split("=")[1]} for tag in tag_texts_top]

    matched_elements = []
    for element in root.iter():
        if element.tag in {"node", "way"}:
            tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}
            for match in top_matches:
                if tags.get(match["k"]) == match["v"]:
                    match_entry = {
                        "type": element.tag,
                        "tags": tags
                    }
                    if element.tag == "node":
                        match_entry["lat"] = element.attrib.get("lat")
                        match_entry["lon"] = element.attrib.get("lon")
                    else:
                        match_entry["id"] = element.attrib.get("id")
                    matched_elements.append(match_entry)
                    break

    location_df = pd.DataFrame(matched_elements)

    start_point = (38.8305, -77.3079)
    nearest_start_node = min(node_lookup, key=lambda nid: geodesic(start_point, node_lookup[nid]).meters)

    if location_df.empty:
        return []

    if location_df.iloc[0]["type"] == "node":
        dest_lat = float(location_df.iloc[0]["lat"])
        dest_lon = float(location_df.iloc[0]["lon"])
    else:
        return []

    destination_coords = [(dest_lat, dest_lon)]

    graph_nodes = set(G.nodes)
    destination_nodes = [
        min(graph_nodes, key=lambda nid: geodesic(dest, node_lookup[nid]).meters)
        for dest in destination_coords
    ]

    shortest_path = None
    min_distance = float("inf")
    for dest in destination_nodes:
        try:
            path = nx.shortest_path(G, source=nearest_start_node, target=dest, weight='weight')
            dist = nx.shortest_path_length(G, source=nearest_start_node, target=dest, weight='weight')
            if dist < min_distance:
                min_distance = dist
                shortest_path = path
        except nx.NetworkXNoPath:
            continue

    path_coords = [node_lookup[nid] for nid in shortest_path] if shortest_path else []
    path_df = pd.DataFrame(path_coords, columns=["lat", "lon"])
    path_df.to_csv("shortest_path_coords.csv", index=False)
    # lat and long returned in tuple format
    # return [{"lat": lati, "lon": long} for lati, long in path_coords]

    # lat and long returned in json format
    return path_df.to_dict()

@app.post('/get_waypoints/')
def bottleapi():
    data = request.json
    user_prompt = data.get("user_prompt")
    waypoints = get_waypoints(user_prompt)
    response.content_type = 'application/json'
    return json.dumps({"waypoints": waypoints})


# run(app, host='0.0.0.0', port=7860, debug=True)
run(app, host='0.0.0.0', port=14550, debug=True)


''' mavlink wip
from pymavlink import mavutil

master = mavutil.mavlink_connection("udp:127.0.0.1:14550")
master.wait_heartbeat()

master.mav.mission_clear_all_send(master.target_system, master.target_component)
master.mav.mission_set_current_send(master.target_system, master.target_component, 0)

n_waypoints = len(path_df)
master.mav.mission_count_send(master.target_system, master.target_component, n_waypoints)

ALTITUDE = 1.0

for i, row in path_df.iterrows():
    master.mav.mission_item_send(
        master.target_system,
        master.target_component,
        i,
        mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT,
        mavutil.mavlink.MAV_CMD_NAV_WAYPOINT,
        0, 1,
        0, 0, 0, 0,
        row["lat"], row["lon"],
        ALTITUDE
    )
    print(f"Sent waypoint {i + 1} at ({row['lat']}, {row['lon']})")

print("waypoints sent")
'''