# -*- coding: utf-8 -*-
"""pathfinding_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SP3P7CLMItx956RYeGmRc5sd2iHGzLe3
"""

#ggplot, R studio, mapillary, centroid problem, multiple stops, priority/clarification questioning, filter out websites, LLM robot summon, construction

import requests
import xml.etree.ElementTree as ET
import json
from collections import defaultdict
from IPython.display import Javascript, display
import base64
import whisper
from sentence_transformers import SentenceTransformer, util
import networkx as nx
from geopy.distance import geodesic
import pandas as pd
import csv
from transformers import pipeline
from openai import OpenAI
import os

"""fetches the latest snapshot of the OSM data for the GMU Campu and writes it into gmu.osm."""

min_lat = 38.82657
min_lon = -77.31182
max_lat = 38.83533
max_lon = -77.30015

def get_osm_file(min_lat, min_lon, max_lat, max_lon):
    url = f"https://overpass-api.de/api/map?bbox={min_lon},{min_lat},{max_lon},{max_lat}"
    return requests.get(url).content

# fetch and store
osm_data = get_osm_file(min_lat, min_lon, max_lat, max_lon)

with open("gmu.osm", "wb") as f:
    f.write(osm_data)

#osm_filename = list(uploaded.keys())[0]
tree = ET.parse('gmu.osm') # parse the OSM file into an XML tree
root = tree.getroot()

tag_dict = defaultdict(set)

# creation of dictionary containing key-value pairs
for element in root.iter():
    if element.tag in {"node", "way", "relation"}:
        for tag in element.findall("tag"):
            k = tag.attrib.get("k")
            v = tag.attrib.get("v", "")  # defaults to "" if missing
            if k is not None:
                tag_dict[k].add(v)

tag_dict_json = {k: sorted(list(v_set)) for k, v_set in tag_dict.items()}

# json file containing all tags sorted by all values of a given key
with open("osm_tags_sorted.json", "w") as f:
    json.dump(tag_dict_json, f, indent=2)

print("success")

"""audio interaface."""

# def save_audio(b64data):
#     header, b64 = b64data.split(',', 1)
#     audio_bytes = base64.b64decode(b64)
#     with open("/content/audio_input.wav", "wb") as f:
#         f.write(audio_bytes)
#     print("Saved audio to /content/audio_input.wav")
#
# output.register_callback('notebook.save_audio', save_audio)

display(Javascript("""
async function recordAudio() {
  const sleep = time => new Promise(res => setTimeout(res, time));
  const b2text = blob => new Promise(res => {
    const reader = new FileReader();
    reader.onloadend = () => res(reader.result);
    reader.readAsDataURL(blob);
  });

  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  const recorder = new MediaRecorder(stream);
  const chunks = [];

  recorder.ondataavailable = e => chunks.push(e.data);
  recorder.start();

  await sleep(5000);  // <-- record for 5 seconds
  recorder.stop();

  await new Promise(res => recorder.onstop = res);
  const audioBlob = new Blob(chunks);
  const base64 = await b2text(audioBlob);
  google.colab.kernel.invokeFunction('notebook.save_audio', [base64], {});
}

recordAudio();
"""))

"""OpenAI STT Whisper"""

model = whisper.load_model("base")
result = model.transcribe("audio_input.wav")
print("Transcription:", result["text"])
whisper_result = result["text"]

"""loads a preprocessed JSON file containing OSM tags organized by key-value pairs, then flattens them into key=value strings. Each tag string is embedded using the all-MiniLM-L6-v2 SentenceTransformer model to create a tag embedding matrix. A user prompt is also embedded using the same model. Cosine similarity is computed between the user prompt embedding and all tag embeddings to identify the most semantically similar tags. The top-k matches are extracted, split into key-value-score dictionaries, and stored in a DataFrame"""

with open("osm_tags_sorted.json", "r") as f:
    tag_dict = json.load(f)
print(tag_dict)

# flatten into key=value combined tags
tag_texts = [f"{k}={v}" for k, values in tag_dict.items() for v in values]
print(tag_texts)

# sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

tag_embeddings = model.encode(tag_texts, convert_to_tensor=True)

# user input
user_prompt = "take me to the library"
#user_prompt = whisper_result
prompt_embedding = model.encode(user_prompt, convert_to_tensor=True)

# compute cosine similarity
cosine_scores = util.cos_sim(prompt_embedding, tag_embeddings)[0]

top_k = 10
top_indices = cosine_scores.argsort(descending=True)[:top_k]
top_matches = [(tag_texts[i], float(cosine_scores[i])) for i in top_indices]

matched_kv = [{"k": tag.split("=")[0], "v": tag.split("=")[1], "score": score} for tag, score in top_matches]

matched_df = pd.DataFrame(matched_kv)

display(matched_df.head(20))
print(matched_df.head(0).to_markdown())

matched_df.to_csv("top_matches.csv", index=False)

from openai import OpenAI
client = OpenAI(api_key='OPENAI_API_KEY')
fine_tuned_model = "ft:gpt-4o-mini-2024-07-18:personal:badger:Bv4XkicP"
guideline = '''Only respond with the name of the percieved destination on the
GMU campus that the user wants to go to.'''
inputllm = user_prompt
#inputllm = whisper_result
response = client.chat.completions.create(
    model=fine_tuned_model,
    messages=[
        {"role": "system", "content": guideline},
        {"role": "user", "content": inputllm}
    ]
)
outputllm = response.choices[0].message.content
print(outputllm)

tree = ET.parse("gmu.osm")
root = tree.getroot()

def find_latlon_by_name(place_name):
    for element in root.iter():
        if element.tag in {"node", "way"}:
            tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}

            # check if the name tag matches the place_name
            if tags.get("name", "").lower() == place_name.lower():
                if element.tag == "node":
                    lat = float(element.attrib["lat"])
                    lon = float(element.attrib["lon"])
                    return {"type": "node", "lat": lat, "lon": lon, "tags": tags}

                elif element.tag == "way":
                    # for a way, get all the node refs and average their coordinates
                    nd_refs = [nd.attrib["ref"] for nd in element.findall("nd")]
                    coords = [node_lookup[ref] for ref in nd_refs if ref in node_lookup]
                    if coords:
                        avg_lat = sum(lat for lat, _ in coords) / len(coords)
                        avg_lon = sum(lon for _, lon in coords) / len(coords)
                        return {"type": "way", "lat": avg_lat, "lon": avg_lon, "tags": tags}
    return None

result = find_latlon_by_name(outputllm)
print(result)

result["lat"], result["lon"]

"""notes: freeze the weights sequentially, upper layers

processes an OpenStreetMap (OSM) XML file to identify and extract geographic elements (specifically nodes and ways) that semantically match the top k key-value tags identified from the user's prompt. It first builds a lookup table mapping node IDs to their latitude and longitude coordinates. Then, it iterates through all relevant elements (node and way) in the OSM file and checks how many of their tags match the top semantic matches from the earlier similarity search. For each matching element, it constructs a result entry containing the element type, all of its tags, and the number of tag matches (match_count). For nodes, coordinates are taken directly from attributes. For ways, it computes the average latitude and longitude based on the coordinates of referenced nodes, providing a centroid approximation. All matched elements are collected and sorted in descending order of match_count, so that elements with the most semantically relevant tags are prioritized. The resulting data is stored in a DataFrame (location_df)
"""

tree = ET.parse("gmu.osm") # parse the OSM file into an XML tree
root = tree.getroot()

# node id; (lat, lon) lookup table
node_coords = {}
for node in root.findall("node"):
    node_id = node.attrib["id"]
    lat = float(node.attrib["lat"])
    lon = float(node.attrib["lon"])
    node_coords[node_id] = (lat, lon)

# limit the number of top (key, value) tag matches to consider
N_top_kv_pairs = 10
top_matches = matched_df.head(N_top_kv_pairs).to_dict("records")

'''
matched_elements = []

for element in root.iter():
  # consider nodes and ways only
    if element.tag in {"node", "way"}:
      # # Extract all tags for the current element
        tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}
        # see if the element matches any of the top (k,v) tag pairs
        for match in top_matches:
            if tags.get(match["k"]) == match["v"]:
                match_entry = {
                    "type": element.tag,
                    "tags": tags
                }
                if element.tag == "node":
                    match_entry["lat"] = element.attrib.get("lat")
                    match_entry["lon"] = element.attrib.get("lon")
                else:
                    match_entry["id"] = element.attrib.get("id")
                matched_elements.append(match_entry)
                break  # avoid duplicate inclusion


for element in root.iter():
    if element.tag in {"node", "way"}:
        tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}
        for match in top_matches:
            if tags.get(match["k"]) == match["v"]:
                match_entry = {
                    "type": element.tag,
                    "tags": tags
                }

                if element.tag == "node":
                    match_entry["lat"] = element.attrib.get("lat")
                    match_entry["lon"] = element.attrib.get("lon")

                elif element.tag == "way":
                    match_entry["id"] = element.attrib.get("id")
                    # Get node references
                    nd_refs = [nd.attrib["ref"] for nd in element.findall("nd")]
                    coords = [node_coords[ref] for ref in nd_refs if ref in node_coords]
                    if coords:
                        avg_lat = sum(lat for lat, _ in coords) / len(coords)
                        avg_lon = sum(lon for _, lon in coords) / len(coords)
                        match_entry["lat"] = avg_lat
                        match_entry["lon"] = avg_lon
                    else:
                        match_entry["lat"] = None
                        match_entry["lon"] = None

                matched_elements.append(match_entry)
                break  # avoid duplicate inclusion
'''
matched_elements = []

for element in root.iter():
    if element.tag in {"node", "way"}:
        tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}

        # count matching (k,v) tags from top_matches
        match_count = sum(1 for match in top_matches if tags.get(match["k"]) == match["v"])
        if match_count == 0:
            continue  # skip elements with no matches

        match_entry = {
            "type": element.tag,
            "tags": tags,
            "match_count": match_count  # store the match count
        }

        if element.tag == "node":
            match_entry["lat"] = element.attrib.get("lat")
            match_entry["lon"] = element.attrib.get("lon")

        elif element.tag == "way":
            match_entry["id"] = element.attrib.get("id")
            nd_refs = [nd.attrib["ref"] for nd in element.findall("nd")]
            coords = [node_coords[ref] for ref in nd_refs if ref in node_coords]
            if coords:
                avg_lat = sum(lat for lat, _ in coords) / len(coords)
                avg_lon = sum(lon for _, lon in coords) / len(coords)
                match_entry["lat"] = avg_lat
                match_entry["lon"] = avg_lon
            else:
                match_entry["lat"] = None
                match_entry["lon"] = None

        matched_elements.append(match_entry)

# sort matched elements by match count (descending)
matched_elements.sort(key=lambda x: x["match_count"], reverse=True)


location_df = pd.DataFrame(matched_elements)
display(location_df)

display(location_df)
location_df.to_csv("top_locations.csv", index=False)

"""Dijkstra-based pathfinding on a pedestrian-accessible graph constructed from OSM data. It begins by parsing an OSM XML file to extract all nodes and their geographic coordinates, storing them in a lookup table. Then, it builds an undirected graph (G) where each node represents a geographic point from the OSM dataset, and edges connect sequential node pairs within way elements that are identified as walkable paths (e.g., footway, path, corridor, pedestrian). To ensure accessibility, it filters out stairs ("steps") and ways that are explicitly marked as not wheelchair-friendly.

Each edge is weighted by the geodesic (real-world) distance between the connected node coordinates. A given starting point (latitude and longitude) is then mapped to its nearest OSM node based on minimum geodesic distance. Similarly, a destination coordinate (extracted from the top-ranked result in a previously created location DataFrame) is matched to its closest node in the walkable graph.

Using Dijkstra’s algorithm, the script computes the shortest path from the start node to each candidate destination node. Among all candidate paths, the one with the smallest total weight (i.e., distance in meters) is selected. If a valid path is found, its corresponding node coordinates are retrieved and assembled into a DataFrame for visualization or further processing. This allows for efficient and accessible routing across a real-world geographic area using structured OSM data.
"""

tree = ET.parse("gmu.osm") # parse the OSM file as an XML tree
root = tree.getroot()

 # lookup table of all nodes and their (lat, lon)
node_lookup = {}
for node in root.findall("node"):
    node_id = node.attrib["id"]
    lat = float(node.attrib["lat"])
    lon = float(node.attrib["lon"])
    node_lookup[node_id] = (lat, lon)

# graph where nodes are OSM nodes and edges represent walkable paths
G = nx.Graph()
for way in root.findall("way"):
    tags = {tag.attrib["k"]: tag.attrib["v"] for tag in way.findall("tag")}
    if ( #preventing steps and encouraging weelchair accessibility
        tags.get("highway") in {"footway", "path", "corridor", "pedestrian"}
        and tags.get("highway") != "steps"
        and tags.get("ramp:wheelchair") != "no"
        and tags.get("wheelchair") != "no"
    ):
    # list of node references that make up this path
        nds = [nd.attrib["ref"] for nd in way.findall("nd")]
        # add each pair of connected nodes as edges with distance as weight
        for i in range(len(nds) - 1):
            n1, n2 = nds[i], nds[i + 1]
            if n1 in node_lookup and n2 in node_lookup:
                coord1, coord2 = node_lookup[n1], node_lookup[n2]
                dist = geodesic(coord1, coord2).meters
                G.add_edge(n1, n2, weight=dist)

# start point
start_point = (38.8295903, -77.3058259)
nearest_start_node = min(node_lookup, key=lambda nid: geodesic(start_point, node_lookup[nid]).meters)

'''
if location_df.iloc[0]["type"] == "node":
    dest_lat = float(location_df.iloc[0]["lat"])
    dest_lon = float(location_df.iloc[0]["lon"])
else:
    dest_lat = None
    dest_lon = None
'''
dest_lat = float(location_df.iloc[0]["lat"])
dest_lon = float(location_df.iloc[0]["lon"])

destination_coords = [(dest_lat, dest_lon)]
#destination_coords =  [(result["lat"], result["lon"])]

# map destination coordinates to closest graph node or nodes
graph_nodes = set(G.nodes)
destination_nodes = [
    min(graph_nodes, key=lambda nid: geodesic(dest, node_lookup[nid]).meters)
    for dest in destination_coords
]

shortest_path = None
min_distance = float("inf")
for dest in destination_nodes:
    try: # dijkstra's
        path = nx.shortest_path(G, source=nearest_start_node, target=dest, weight='weight')
        dist = nx.shortest_path_length(G, source=nearest_start_node, target=dest, weight='weight')
        if dist < min_distance:
            min_distance = dist
            shortest_path = path
    except nx.NetworkXNoPath:
        continue

path_coords = [node_lookup[nid] for nid in shortest_path] if shortest_path else []
path_df = pd.DataFrame(path_coords, columns=["lat", "lon"])
path_df.head(20)

output_path = "shortest_path_coords.csv"
path_df.to_csv(output_path, index=False)

output_path

csv_path = 'shortest_path_coords.csv'
df = pd.read_csv(csv_path)


df.columns = [col.strip().lower() for col in df.columns]
if 'lat' in df.columns and 'lon' in df.columns:
    df.rename(columns={'lat': 'latitude', 'lon': 'longitude'}, inplace=True)

# Waypoint header
waypoint_lines = ["QGC WPL 110"]

# Generate waypoints
for idx, row in df.iterrows():
    line = f"{idx}\t0\t3\t16\t0\t0\t0\t0\t{row['latitude']}\t{row['longitude']}\t0.000000\t1"
    waypoint_lines.append(line)

# Save to file
with open("converted_waypoints.txt", "w") as f:
    f.write("\n".join(waypoint_lines))

print("Waypoints file generated; converted_waypoints.txt")

prompts = [
    "I want to drink a beverage",
    "I want to purchase a beverage",
    "I want to read a book",
    "I want to purchase a book",
    "I want to get a sandwich",
    "I want to study in silence",
    "I want to buy snacks",
    "I want to get Mexican food",
    "I want to exercise",
    "I want to swim",
    "I want to relax",
    "I want to watch sports",
    "I want to play sports",
    "I want to get Halal food",
    "I want to get a bagel",
    "I want to get a pizza",
    "I want to learn about Geoinformation Science",
    "I want to tend to a plant",
    "I want to withdraw money",
    "I want to file a police report",
    "I want to study engineering",
    "I want to learn art",
    "I want to go to a dormitory",
    "I want to go to first year student housing",
    "I want to go to an upper level residence hall",
    "I want to study Economics",
    "I want to study inside near Mason Pond",
    "I want to watch a live performance",
    "I want to do laundry",
    "I want to study business",
    "I want to study History",
    "I want to conduct lab research",
    "I want to go to administration",
    "I want to attend a large lecture",
    "I want to go to human resources",
    "I want to study astronomy",
    "I want to research in a dedicated space",
    "I want to study kinesiology",
    "I want to go to a resident kitchen",
    "I want to update my Mason ID",
    "I want to play Soccer",
    "I want to play Baseball",
    "I want to play Bocce",
    "I want to see flowers",
    "I want to store something large",
    "I want to admire a statue",
    "I want to drink tea",
    "I want to 3D print a component",
    "I want to drink coffee",
    "I want to get a perking permit"
]

import time
from openai import OpenAI



fine_tuned_model = "ft:gpt-4o-mini-2024-07-18:personal:badger:Bv4XkicP"

with open("guidelines.txt", "r") as f:
    guideline = f.read()

results = []
times = []

for prompt in prompts:
    start_time = time.time()

    response = client.chat.completions.create(
        model=fine_tuned_model,
        messages=[
            {"role": "system", "content": guideline},
            {"role": "user", "content": prompt}
        ]
    )

    end_time = time.time()
    elapsed = end_time - start_time
    times.append(elapsed)

    output = response.choices[0].message.content.strip()
    results.append({
        "prompt": prompt,
        "fine_tuned_output": output,
        "response_time_sec": elapsed
    })

    print(f"{prompt} answered in {elapsed:.2f} seconds")

average_time = sum(times) / len(times)
print(f"\nAverage response time: {average_time:.2f} seconds")

print(results)

tree = ET.parse("gmu.osm")
root = tree.getroot()
times_slm = []

tag_dict = defaultdict(set)
for element in root.iter():
    if element.tag in {"node", "way", "relation"}:
        for tag in element.findall("tag"):
            k = tag.attrib.get("k")
            v = tag.attrib.get("v", "")
            if k is not None:
                tag_dict[k].add(v)

tag_dict_json = {k: sorted(list(v)) for k, v in tag_dict.items()}
tag_texts = [f"{k}={v}" for k, values in tag_dict_json.items() for v in values]

model = SentenceTransformer("all-MiniLM-L6-v2")
tag_embeddings = model.encode(tag_texts, convert_to_tensor=True)

for entry in results:
    start_time = time.time()
    user_prompt = entry["prompt"]

    prompt_embedding = model.encode(user_prompt, convert_to_tensor=True)
    cosine_scores = util.cos_sim(prompt_embedding, tag_embeddings)[0]

    top_k = 10
    top_indices = cosine_scores.argsort(descending=True)[:top_k]
    top_matches = [(tag_texts[i], float(cosine_scores[i])) for i in top_indices]
    matched_kv = [{"k": tag.split("=")[0], "v": tag.split("=")[1], "score": score} for tag, score in top_matches]

    matched_elements = []
    for element in root.iter():
        if element.tag in {"node", "way"}:
            tags = {tag.attrib["k"]: tag.attrib["v"] for tag in element.findall("tag")}
            if 'confucius' in tags.get('name', '').lower():
              continue
            match_count = sum(1 for match in matched_kv if tags.get(match["k"]) == match["v"])
            if match_count > 0:
                matched_elements.append({
                    "type": element.tag,
                    "tags": tags,
                    "match_count": match_count
                })

    matched_elements.sort(key=lambda x: x["match_count"], reverse=True)
    '''
    if matched_elements:
        slm_output = matched_elements[0]["tags"].get("name", "Unnamed")
    else:
        slm_output = "No matching location found"
    entry["slm_output"] = slm_output

    if matched_elements:
      top_tags = matched_elements[0]["tags"]
      if "name" in top_tags:
          slm_output = top_tags["name"]
      else:
          slm_output = "Unnamed"
          print(f"Unnamed result for prompt: {user_prompt}")
          print("Full tags for this element:")
          for k, v in top_tags.items():
              print(f"{k}: {v}")
          print("-" * 40)
    else:
      slm_output = "No matching location found"
    '''
    # Determine SLM output by searching matched elements until one has a name
    slm_output = "No matching location found"

    for match in matched_elements:
        name = match["tags"].get("name")
        if name:
            slm_output = name
            break
    if slm_output == "No matching location found":
        print(f"No named result for prompt: {user_prompt}")
        if matched_elements:
            print("Top element's tags:")
            for k, v in matched_elements[0]["tags"].items():
                print(f"{k}: {v}")
            print("-" * 40)
    entry["slm_output"] = slm_output
    end_time = time.time()
    elapsed = end_time - start_time
    times_slm.append(elapsed)

average_time_slm = sum(times_slm) / len(times_slm)
print(f"\nAverage response time: {average_time_slm:.2f} seconds")

pd.DataFrame(results).to_csv("slm_vs_llm_results.csv", index=False)